# Generated by Django 4.1.3 on 2022-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_developers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='picture',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
