# Generated by Django 4.1.3 on 2022-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_echodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='echodata',
            name='aid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='echodata',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='echodata',
            name='log',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='echodata',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='echodata',
            table='Gps_data',
        ),
    ]
