# Generated by Django 4.1.3 on 2022-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_echodata_aid_echodata_lat_echodata_log_echodata_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echodata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
